Function Get-SPSitePagesContent{
 <#
		.SYNOPSIS
		Return all pages of a site collection and their content
		
		.DESCRIPTION
		Return an object of all pages of a library and their content using the REST API. The function assumes you already made a connection to a site.  
		
		.PARAMETER SiteURL
		The entire URL with tenant and site
		
		.PARAMETER Library
		the library whose pages you would like to obtain

		.EXAMPLE
		Get-SPSitePagesContent -SiteURL "https://YourTenant.sharepoint.com/sites/inf" -Library "Pages%20du%20site" 

		.EXAMPLE
		$Pages = Get-SPSitePagesContent -SiteURL "https://YourTenant.sharepoint.com"
		
		.NOTES
		FunctionName : Get-SPSitePagesContent
		Created by   : Yann Greder
		Date Coded   : 09/24/2020
		Source       : 
#>
		
    Param
    (
        [Parameter(Mandatory=$true)]$SiteURL,
        [Parameter(Mandatory=$false)]$Library = "SitePages"
    )

    $Web = Invoke-PnPSPRestMethod -url "$SiteURL/_api/web/lists/getbytitle('$Library')/Items" 

    $ArrayPages = @()

    # for unknown reason, the $web object is case sensitive
    foreach($Page in $web.value){
        $ObjPage = [PSCustomObject]@{
            Title    = $Page.Title
            Created  = $Page.Created
            Modified = $Page.Modified
            Content  = $Page.CanvasContent1
        }
        $ArrayPages += $ObjPage 
    }

    Return $ArrayPages
}

# $Pages = Get-SPSitePagesContent -SiteURL "https://fvecorp.sharepoint.com/sites/inf/" -Library "Pages%20du%20site" 

# SIG # Begin signature block
# MIIROQYJKoZIhvcNAQcCoIIRKjCCESYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUvX/JwyD1ppk7CqQ3J5sn6Awo
# eWKggg6zMIIHFTCCBP2gAwIBAgITHQAACtFAvjTDFSExqAAAAAAK0TANBgkqhkiG
# 9w0BAQsFADA4MQswCQYDVQQGEwJDSDEMMAoGA1UEChMDRlZFMRswGQYDVQQDExJG
# VkUtSXNzdWVyLUNBLVNoYTIwHhcNMjAwNTE0MDYzMTI0WhcNMjQwNTEzMDYzMTI0
# WjAlMSMwIQYDVQQDDBpGVkVfUG93ZXJTaGVsbF8yMDIwX1NIQTI1NjCCASIwDQYJ
# KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKBGjjvorDOjj0Lbgf0VWcdTtIH9H+wA
# 7wrTcJCZGFWfxtnoEz5sUg7u1KALTehEI3OXnRb9a20iqq9RJKivQ/mjbBUGc1e7
# k4QAzXYj5triQn0jLv2ACa238R5wC/BFfUo+zYfgTRCSVNUb1F9lBSNzv3Z58ZHx
# 8c7xwvnyi7H2LfDLGJdKl4y17lfd9Gqjl3H2CkMaiccW9OYa8XPFFOxydOC0eHcQ
# lnc0KKE11+Ufs7uq7IdbIRQDGHZKxVmf1eDhdsb7HUpxqr/b0mXiqhTRjIvIpv3n
# UIT9X+CSaOF3iIC4JJm1aNiLtZvltLaDGwCk5Nn739i7+7rvH2RRcw8CAwEAAaOC
# AykwggMlMD0GCSsGAQQBgjcVBwQwMC4GJisGAQQBgjcVCIKDnUWHnogigZGTMIPC
# 2jeBg8YGTYaoql6B95xWAgFkAgEPMBMGA1UdJQQMMAoGCCsGAQUFBwMDMA4GA1Ud
# DwEB/wQEAwIHgDAbBgkrBgEEAYI3FQoEDjAMMAoGCCsGAQUFBwMDMB0GA1UdDgQW
# BBRHUxXwDM6m3B6ligB2NL/HdYp3ozAlBgNVHREEHjAcghpGVkVfUG93ZXJTaGVs
# bF8yMDIwX1NIQTI1NjAfBgNVHSMEGDAWgBS8OoUOcc0nS/p/sR6M+ZVfwRO2MjCC
# AQYGA1UdHwSB/jCB+zCB+KCB9aCB8oYxaHR0cDovL3ZhLmZlZG5ldC5sb2NhbC9j
# ZHAvRlZFLUlzc3Vlci1DQS1TaGEyLmNybIaBvGxkYXA6Ly8vQ049RlZFLUlzc3Vl
# ci1DQS1TaGEyLENOPUZFVE8xUzAwNyxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIw
# U2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1mZWRuZXQs
# REM9bG9jYWw/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENs
# YXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MIIBLwYIKwYBBQUHAQEEggEhMIIBHTA9
# BggrBgEFBQcwAoYxaHR0cDovL3ZhLmZlZG5ldC5sb2NhbC9haWEvRlZFLUlzc3Vl
# ci1DQS1TaGEyLmNydDCBsgYIKwYBBQUHMAKGgaVsZGFwOi8vL0NOPUZWRS1Jc3N1
# ZXItQ0EtU2hhMixDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049
# U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1mZWRuZXQsREM9bG9jYWw/Y0FD
# ZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3Jp
# dHkwJwYIKwYBBQUHMAGGG2h0dHA6Ly92YS5mZWRuZXQubG9jYWwvb2NzcDANBgkq
# hkiG9w0BAQsFAAOCAgEAFKlms7NDKFl2cGZeglWQW22UfCOi0bOUuJg1cAB5ajJ/
# t/QqoXvAaIzlHyKzuBY66n888d5yLoaHE0XjxVvm/ae3R0QHvGoBTT2UCuK7mfEe
# Xv32cORTVgAc/MPLQEtav+2EqLMup8Ghm4RtuxpmWQfmzxnz3j9aZO2t4u/iEbpj
# il/XX2ahUqg1KUo47AIrr4jXPy/5khTK4gW28UbHWmSajIIQMLisVdbNrD+9xQMc
# qGUglSVy0lrJl4heL0r533uf9VRS2Sl8PXnYYEyakWS15+bOKd+j71RfJ6SeQtTg
# 35netTV3etr3BuhYTTZLvdA0k+YljQFa8cdyT+0jR6n1lbtZTqCfjv63SPQOf/fb
# 9sASTH9MWebZmSebWXOkQv5aK++GtwczWaAhxUulAmZ1CIzQN6OjvVbp9wpK7VLo
# 96lmQm9aXHcw355uW8oErcMJr0EItPKMFSxaT8BFlAD3ii5xSfbCrwOWLQ//H+gC
# mq87E8sTwx9EdU9BD5NaRtMkIF0pgQ1YqTYJ336wan2+ctk89XdyDyW8/IgfsNEf
# g0cNQ1ji0lLm3zekuk/346ayoPky3v2SawJ62iUOcwrpP0+Aog2Zhu/afqqWfztj
# 1/FNKnhQ+2IgsyIYDhiWQKwK1VhUuFPu/2so22p+/NnHBGy1C5zLgQlc1fLLk2Aw
# ggeWMIIFfqADAgECAhMnAAAAAyFVpU7QN9teAAAAAAADMA0GCSqGSIb3DQEBCwUA
# MDYxCzAJBgNVBAYTAkNIMQwwCgYDVQQKEwNGVkUxGTAXBgNVBAMTEEZWRS1Sb290
# LUNBLVNoYTIwHhcNMTYwNDA4MTIwNzQwWhcNMzYwNDA4MTIxNzQwWjA4MQswCQYD
# VQQGEwJDSDEMMAoGA1UEChMDRlZFMRswGQYDVQQDExJGVkUtSXNzdWVyLUNBLVNo
# YTIwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCt1vSa649UE8BQkGm+
# QDo7t0WDzBVybMXOCXviN8ais9UV7a4Ra0WyIo/X6HzmKgd38P0NV0tR9sy3qHu3
# +SpMy/87Fdqjqm7yx1+MVMGBJ+ONzCKdP7C7e/n4iEj6cfFZE8zL52GmjFyuZCTN
# KsN9NyPZURbSSYU8Wgv9GamcqNKwCEDr03qsjeN7cdn+ftgCCraxsvJByZQ3Qmck
# NKOTkCiDgGIWhjuPuNUM0KaVCI1MltxiyNLPiLjrVQIgSi6VNd3WWIfhwI0IE5rU
# 6sIOE/D1TcdNGWOWON3HrkseSCZ3AJBPHsN+y2T3uwCWQd8yM617aEeYiKVRKE0B
# aEIBaaXrOcelgWt7mGm/asZ/0J5wiQECSH25mEuY67r+e3QOl9sMpXtLuDoCbksZ
# 1fFaMdsxK/CuO1aAmlK74R8LnZx4khrbdDt8GMYrRIOc/KlBAknpyLBZJN6aT+k9
# hnwsXu/uxF6sygx+XLN0Tm3ZyVCn9Pi+ilxYXXnwEacyyTP2n5/uPQ9EBK2FlQdA
# okPVL45A6c3IuQGQu3+j/ArJFrTu4AA0GRB6IjTr8UcAb8X5nGrDqGrQ8/pEFoWg
# nz1cQk6fuP2HBAheDAMzbI7nQwATx0aGFu9ES6CJrsOJK7QrcDxSknGzTHrC1oSz
# ZjmFYliDlZSMmn+A5Cki+WO+MwIDAQABo4ICmTCCApUwEAYJKwYBBAGCNxUBBAMC
# AQAwHQYDVR0OBBYEFLw6hQ5xzSdL+n+xHoz5lV/BE7YyMBkGCSsGAQQBgjcUAgQM
# HgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1Ud
# IwQYMBaAFNSJgUX3JRtX/P/MHbh83sd8qvVYMIIBAgYDVR0fBIH6MIH3MIH0oIHx
# oIHuhi9odHRwOi8vdmEuZmVkbmV0LmxvY2FsL2NkcC9GVkUtUm9vdC1DQS1TaGEy
# LmNybIaBumxkYXA6Ly8vQ049RlZFLVJvb3QtQ0EtU2hhMixDTj1GRVRPMVMwMDYs
# Q049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENO
# PUNvbmZpZ3VyYXRpb24sREM9ZmVkbmV0LERDPWxvY2FsP2NlcnRpZmljYXRlUmV2
# b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2lu
# dDCCAQAGCCsGAQUFBwEBBIHzMIHwMDsGCCsGAQUFBzAChi9odHRwOi8vdmEuZmVk
# bmV0LmxvY2FsL2FpYS9GVkUtUm9vdC1DQS1TaGEyLmNydDCBsAYIKwYBBQUHMAKG
# gaNsZGFwOi8vL0NOPUZWRS1Sb290LUNBLVNoYTIsQ049QUlBLENOPVB1YmxpYyUy
# MEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9
# ZmVkbmV0LERDPWxvY2FsP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1j
# ZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MA0GCSqGSIb3DQEBCwUAA4ICAQCmwFXDp5fl
# TtCG+AnSgq7QOgG3W8vAEzRcNKC5Kxgpoj7al1kNFKnB2EWg4RUMy4mvxfqW7iEq
# fN71jBkA2k5/+i5Xh7blHiyFsO4W3DyLLqAcdlq+MKxfak5MXMfIL0PbCyEshz+J
# wxH61c+WAEV4POHyB2waRk3SFBKaBHlr4mMN5vqzctgfyGylpGmLYYORk4TBivH8
# cb5EbUp4P6qhOImOTwseZVgQ4J+4SJL3uNrvKSQvU00aZyPXnXBIgKV0dFj6Pbhf
# 7iLqof4oN+A9jv/342ecrVSV4VWDJ54SyaDZ3XP8XhKbXQ5rigTV9Ea6kNAZCtNG
# A95zN8paL+2voAaRSA7ubnPN5mVRLV95V0R36ziQ9xrhGt77uhh3Cx24/h5YpJ/C
# 1OBWs4ofIWS1ksdPvshzPZfrstiRdzJSgaX2hJkFL/CldaE75u/VQzKcrmKaXpWj
# ZUTi/4+k8lLLk2jh8xrE1De2C63Am18iueFdpk5eMI20x6L8W351hv7XRevbLagB
# +M/LHd0Y6r41Iov9FT9DvSA+MOVo2850K9Dlx00K1azGDWlDW9ZmtWXuZtdY5iGz
# AX+awBuCKzNzwm0Y5zgomTb9CCTfaGRw2BqCxRNic1B/Hlbsfd4dxMocKpQzs1Ee
# MfrXKuZsoYONHE4WXS49M2fPO+Wq5HpJvDGCAfAwggHsAgEBME8wODELMAkGA1UE
# BhMCQ0gxDDAKBgNVBAoTA0ZWRTEbMBkGA1UEAxMSRlZFLUlzc3Vlci1DQS1TaGEy
# AhMdAAAK0UC+NMMVITGoAAAAAArRMAkGBSsOAwIaBQCgeDAYBgorBgEEAYI3AgEM
# MQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQB
# gjcCAQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBQ/0s7jgoi8Xbhe
# NRZ6iV15Dlvm2TANBgkqhkiG9w0BAQEFAASCAQBYHGDsWpQ2on381qzR2Keq9dQg
# +kxmD7eZWapXBXJFY3a5iJJBasXbrsoz9Ka9p2a/HerdFUPsnm/BGmzGd6JzMXlM
# 2RgOqf298yJQ7Urnk53L0QA3n7s0Vjlg+kk9uoIaT4RlaC3L/5TS8IxsBwbd59hv
# RfUIElAZz0ylT0dfy3Fq8tXLPVIshuUMbIo7p6ocQJI2CydJ5IZ8x52FWP52wzky
# ELY/eTkOwLitJDhGuguWL8u8XVRPeeILE/wfK8yjNjW0+fo5YZiWKv7RPCSeh6lL
# loqMcLSY6Kq+Sy0TvTxQTBSddGxdbV32m3buC2uMlP99qhw+7RidICSzpEc7
# SIG # End signature block
